"""Minor changes

Revision ID: 59629a6c067b
Revises: 7f71803a64e6
Create Date: 2023-06-06 02:29:38.395777

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '59629a6c067b'
down_revision = '7f71803a64e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
