"""UserInfo fixes

Revision ID: 6c01ca5dcead
Revises: ae6b4881f3cf
Create Date: 2023-06-05 23:26:24.700856

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6c01ca5dcead'
down_revision = 'ae6b4881f3cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
