"""Favourite column added

Revision ID: 7e7bce7b928d
Revises: 59629a6c067b
Create Date: 2023-06-07 23:00:13.987213

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '7e7bce7b928d'
down_revision = '59629a6c067b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
