"""Minor fixes

Revision ID: 7ed112062a84
Revises: 6c01ca5dcead
Create Date: 2023-06-05 23:34:30.152483

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '7ed112062a84'
down_revision = '6c01ca5dcead'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('favourite', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_info', 'favourite')
    # ### end Alembic commands ###
