"""Minor changes

Revision ID: ae6b4881f3cf
Revises: ac96a6ec1d83
Create Date: 2023-06-02 23:18:10.161536

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ae6b4881f3cf'
down_revision = 'ac96a6ec1d83'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_info_favourite_fkey', 'user_info', type_='foreignkey')
    op.drop_column('user_info', 'favourite')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('favourite', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('user_info_favourite_fkey', 'user_info', 'project', ['favourite'], ['id'])
    # ### end Alembic commands ###
