"""Favourite column added

Revision ID: dc8adad29609
Revises: 7e7bce7b928d
Create Date: 2023-06-07 23:12:45.612556

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'dc8adad29609'
down_revision = '7e7bce7b928d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
